### ISSUE TITLE
No longer working after upgrading to Flutter 3.24.3

### ISSUE THREAD

**Issue by michaeljajou** [sommye-ctr/video_cast#5]
After upgrading to Flutter 3.24.3, the chrome cast button is no longer working. It just remains in a disabled state - and the on session started callback never gets fired. video_cast: ^1.0.2

```
version: 1.3.0+51
environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^14.2.7
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  permission_handler: ^11.3.1
  flutter_svg: ^2.0.7
  video_player: ^2.7.1
  image_picker: ^1.0.4
  email_validator: ^3.0.0
  app_settings: ^5.0.0
  photo_view: ^0.15.0
  share_plus: ^10.0.2
  image_cropper: ^8.0.2
  gradient_borders: ^1.0.0
  flutter_email_sender: ^6.0.2
  in_app_review: ^2.0.6
  flutter_to_airplay: ^2.0.4
  cloud_firestore: ^5.4.2
  cloud_functions: ^5.1.2
  google_sign_in: ^6.1.5
  open_mail_app: ^0.4.5
  equatable: ^2.0.5
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  http: ^1.1.0
  visibility_detector: ^0.4.0+2
  geolocator: ^13.0.1
  path_provider: ^2.1.1
  purchases_flutter: ^8.1.2
  flutter_dotenv: ^5.1.0
  simple_gradient_text: ^1.3.0
  shared_preferences: ^2.2.2
  package_info_plus: ^8.0.2
  wakelock_plus: ^1.1.4
  video_cast: ^1.0.2
  intl_phone_number_input: ^0.7.4
  health: ^11.0.0
  webview_flutter: ^4.7.0
  mixpanel_flutter: ^2.2.0
  flutter_mentions: ^2.0.1
  flutter_slidable: ^3.1.0
  url_launcher: ^6.3.0
  firebase_core: ^3.5.0
  firebase_analytics: ^11.3.2
  firebase_auth: ^5.3.0
  firebase_storage: ^12.3.1
  firebase_dynamic_links: ^6.0.7
  firebase_messaging: ^15.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/graphics/
    - assets/icons/
    - assets/videos/
    - .env
  fonts:
    - family: Futura
      fonts:
        - asset: fonts/futura/light.otf
          weight: 200
        - asset: fonts/futura/book.otf
          weight: 300
        - asset: fonts/futura/regular.ttf
          weight: 400
        - asset: fonts/futura/medium.otf
          weight: 500
        - asset: fonts/futura/bold.otf
          weight: 600
        - asset: fonts/futura/heavy.otf
          weight: 700
        - asset: fonts/futura/black.ttf
          weight: 800

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/icons/app_logo.png"
  image_path_android: "assets/icons/android_app_logo.png"
  adaptive_icon_foreground: "assets/icons/android_app_logo.png"
  adaptive_icon_background: "assets/icons/app_logo_background.png"

flutter_native_splash:
  image: assets/icons/app_logo_background.png
  color: 42a5f5
  android: true
  ios: false
```
